### ISSUE TITLE
【質問】LINEログインを実装したがProfileが編集できない件について

### ISSUE THREAD

**Issue by monaka0309** [monaka0309/nanikiru#161]
# LINEログインを実装したがプロフィールが変更できない。
　LINEログイン機能を実装しています。LINEログインが完了し、LINEの名前をアプリに反映させることができました。
　しかし、マイページからnameとimageを更新することができません。UserテーブルとAuthenticationテーブルは関連付けられていつの思うのですが。どのように修正したらいいでしょうか。
　現在は開発環境で修正をしています。

## 環境
Ruby 3.2.2
Rails 7.0.8
gem 'sorcery'
gem 'omniauth-auth0'
gem 'omniauth-line'
gem 'omniauth-rails_csrf_protection'

## スキーマファイル
```
ActiveRecord::Schema[7.0].define(version: 2024_04_12_011636) do

  create_table "authentications", force: :cascade do |t|
    t.integer "user_id", null: false
    t.string "provider", null: false
    t.string "uid", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["provider", "uid"], name: "index_authentications_on_provider_and_uid"
  end

  create_table "comments", force: :cascade do |t|
    t.text "content"
    t.integer "user_id"
    t.integer "post_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "favorites", force: :cascade do |t|
    t.integer "user_id"
    t.integer "post_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "post_tiles", force: :cascade do |t|
    t.bigint "post_id", null: false
    t.bigint "tile_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["post_id"], name: "index_post_tiles_on_post_id"
    t.index ["tile_id"], name: "index_post_tiles_on_tile_id"
  end

  create_table "posts", force: :cascade do |t|
    t.text "content"
    t.string "image"
    t.bigint "user_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_posts_on_user_id"
  end

  create_table "tiles", force: :cascade do |t|
    t.string "name", null: false
    t.string "image_path", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "image"
    t.index ["name"], name: "index_tiles_on_name", unique: true
  end

  create_table "users", force: :cascade do |t|
    t.string "name"
    t.string "nickname"
    t.string "email"
    t.string "crypted_password"
    t.string "salt"
    t.string "image"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
  end

  create_table "votes", force: :cascade do |t|
    t.bigint "user_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "post_id"
    t.string "choice"
    t.bigint "post_tile_id"
    t.index ["post_id"], name: "index_votes_on_post_id"
    t.index ["post_tile_id"], name: "index_votes_on_post_tile_id"
    t.index ["user_id"], name: "index_votes_on_user_id"
  end

  add_foreign_key "post_tiles", "tiles"
  add_foreign_key "posts", "users"
end
```
### sorceryのサブモジュールを追加
`authentications`テーブルの追加。上記スキーマファイル参照。

### sorcery.rb
```
# frozen_string_literal: true

Rails.application.config.sorcery.submodules = [:external]

Rails.application.config.sorcery.configure do |config|

  # -- external --
  config.external_providers = %i[line]

  config.line.key = Rails.application.credentials.dig(:line, :channel_id)
  config.line.secret = Rails.application.credentials.dig(:line, :channel_secret)
  # config.line.callback_url = 'https://www.nanikiru-mahjong.com/oauth/callback?provider=line'
  config.line.callback_url = 'http://localhost:3000/oauth/callback?provider=line'
  # config.line.callback_url = Settings.sorcery[:line_callback_url]
  config.line.scope = 'profile'
  # config.line.bot_prompt = "normal"(LINEログイン時に公式アカウントを自動追加する機能)
  config.line.user_info_mapping = {name: 'displayName'}

  # --- user config ---
  config.user_config do |user|

    user.stretches = 1 if Rails.env.test?

    user.authentications_class = Authentication

  end

  config.user_class = 'User'
end
```
### モデル
```
# authenticaiton.rb

class Authentication < ApplicationRecord
    belongs_to :user
end
```

```
# user.rb

class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications
end
```
### view
```
# app/views/users/user_sessions.html.erb

<%= link_to 'Login with Line', auth_at_provider_path(:provider => :line) %>
```
## oauthコントローラーの作成
```
class OauthsController < ApplicationController
  # skip_before_action :require_login, raise: false

  # sends the user on a trip to the provider,
  # and after authorizing there back to the callback url.
  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule
        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end

  #example for Rails 4: add private method below and use "auth_params[:provider]" in place of
  #"params[:provider] above.

  # private

  # def auth_params
  #   params.permit(:code, :provider)
  # end
end
```
## routes.rb
```
# config/routes.rb

post "oauth/callback" => "oauths#callback"
get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
```
## config/initializers/credential.yml.enc
```
line:
  channel_id: チャネルidの値
  channel_secret: チャネルシークレットの値
```

**Comment by kenchasonakai** [comment]
どういう流れて処理を行えば更新できるはずなのかと、現状なにが原因で更新が行えない状態なのか、更新が行えないとはどう言う状態なのか教えていただけますか？

**Comment by monaka0309** [comment]
### LINEログインしたユーザー
[![Image from Gyazo](https://i.gyazo.com/8d7c823da5cc2e553ab36dfa3cdada4a.gif)](https://gyazo.com/8d7c823da5cc2e553ab36dfa3cdada4a)

コンソールで確認するとカラム名はnameになっているのでマイページから更新できると考えています。

```
 #<User:0x00000001100cc770
  id: 17,
  name: "仲 竜之介",
  nickname: nil,
  email: nil,
  crypted_password: nil,
  salt: nil,
  image: nil,
  created_at: Mon, 15 Apr 2024 23:27:09.607886000 JST +09:00,
  updated_at: Mon, 15 Apr 2024 23:27:09.607886000 JST +09:00>]
```

私の考えとしては、LINEログインの場合保存されるテーブルがUserテーブルではなく、AuthenticationテーブルのためUserを更新するProfileの編集画面ではプロフィールが更新されないと考えています。

```
  create_table "authentications", force: :cascade do |t|
    t.integer "user_id", null: false
    t.string "provider", null: false
    t.string "uid", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["provider", "uid"], name: "index_authentications_on_provider_and_uid"
  end

  create_table "users", force: :cascade do |t|
    t.string "name"
    t.string "nickname"
    t.string "email"
    t.string "crypted_password"
    t.string "salt"
    t.string "image"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
  end
```

**Comment by kenchasonakai** [comment]
Authenticationは外部認証に必要な情報を保存するところなので普通にProfileコントローラーからusersテーブルの内容を更新する処理をすればusersテーブルのnameカラムを更新できるかと思います

**Comment by monaka0309** [comment]
ありがとうございます。
Profileコントローラーは下記のようになっています。
これでUserテーブルは更新できると思っていますのですが、別の箇所に問題があるのでしょうか。

profiles_controller.rb
```
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]
  before_action :require_login, only: %i[show]

  def show
    @name = current_user.name
    @posts = current_user.posts.includes(:user).page(params[:page]).per(10).order(created_at: :desc)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path(@profile)
    else
      flash.now[:danger] = 'ユーザーを更新できませんでした'
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :name, :image)
  end
end
```

**Comment by kenchasonakai** [comment]
user_paramsの値が自分の想定通りになっていれば更新はできると思います

ただ、redirect_toのところでprofileの変数定義してないのでエラーが出たりしそうな気はします

**Comment by kenchasonakai** [comment]
emailの値が何も入っていないことによるバリデーションエラーな気がしますね

user.updateの前にデバッグツールを置いて処理を止めて

```
@user.update(user_params)
@user.valid?
@user.errors.full_messages
```

とかやると何で引っかかってるのか確認できるかなと思います

**Comment by monaka0309** [comment]
プロフィール更新時のログを確認すると`"authenticity_token"=>"[FILTERED]"`となっていました。
viewファイルにて`form_with`で定義しているのですが、書き方を変えるべきでしょうか。

```
Started PATCH "/profile" for ::1 at 2024-04-16 13:42:56 +0900
13:42:56 web.1  | Processing by ProfilesController#update as TURBO_STREAM
13:42:56 web.1  |   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"name"=>"仲 竜之介"}, "commit"=>"更新"}
13:42:56 web.1  |   User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 17], ["LIMIT", 1]]
13:42:56 web.1  |   ↳ app/controllers/profiles_controller.rb:27:in `set_user'
13:42:56 web.1  |   User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 17], ["LIMIT", 1]]
13:42:56 web.1  |   ↳ app/controllers/profiles_controller.rb:27:in `set_user'
13:42:56 web.1  |   TRANSACTION (1.1ms)  BEGIN
13:42:56 web.1  |   ↳ app/controllers/profiles_controller.rb:16:in `update'
13:42:56 web.1  |   User Exists? (0.6ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" IS NULL AND "users"."id" != $1 LIMIT $2  [["id", 17], ["LIMIT", 1]]
13:42:56 web.1  |   ↳ app/controllers/profiles_controller.rb:16:in `update'
13:42:56 web.1  |   TRANSACTION (0.2ms)  ROLLBACK
13:42:56 web.1  |   ↳ app/controllers/profiles_controller.rb:16:in `update'
13:42:56 web.1  |   Rendering layout layouts/application.html.erb
13:42:56 web.1  |   Rendering profiles/edit.html.erb within layouts/application
13:42:56 web.1  |   Rendered layouts/_header.html.erb (Duration: 0.3ms | Allocations: 90)
13:42:56 web.1  |   Rendered layouts/_sidebar.html.erb (Duration: 36.2ms | Allocations: 878)
13:42:56 web.1  |   Rendered layouts/_footer.html.erb (Duration: 0.1ms | Allocations: 8)
13:42:56 web.1  |   Rendered profiles/edit.html.erb within layouts/application (Duration: 39.1ms | Allocations: 2151)
13:42:56 web.1  |   Rendered layout layouts/application.html.erb (Duration: 50.5ms | Allocations: 6955)
13:42:56 web.1  | Completed 200 OK in 79ms (Views: 51.2ms | ActiveRecord: 2.7ms | Allocations: 12407)
```

views/posts/profiles/edit.html.erb
```
<!DOCTYPE html>
<html lang="ja">
<head>
</head>
<body class="bg-gray-200 font-sans w-full">
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidebar' %>

    <main class="container mx-auto px-6 text-gray-600 mb-10 w-full w-11/12 sm:w-5/6 mx-auto">
        <%# プロフィール %>
        <h1 class="text-2xl font-mono mb-2 font-mono ">プロフィール編集</h1>
            <%= form_with model: @user, url: profile_path, local: true do |f| %>
                <%#  エラーメッセージ %>
                <% if @user.errors.any? %>
                    <div id="error_explanation">
                        <ul class="font-mono">
                        <% @user.errors.full_messages.each do |message| %>
                            <li class="error-message"><%= message %></li>
                        <% end %>
                        </ul>
                    </div>
                <% end %>
                <div class="font-mono w-11/12 sm:w-5/6 mx-auto">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'block text-gray-900 bg-white rounded-lg border border-gray-300 px-3 py-2 mb-3 w-full' %>

                    <div class="mb-5">
                        <%= f.label :image, "プロフィール画像" %><br>
                        <%= f.file_field :image, accept: "image/jpg,image/jpeg,image/gif,image/png,image/webp", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight bg-gray-100" %>
                        <div id="image-preview" class="font-mono">
                            <% if @user.image? %>
                                <%= image_tag current_user.image.url, class: 'rounded-full mb-3  border border-1 border-gray-500'%>
                            <% end %>
                        </div>
                    </div>
                    <%= f.submit "更新", class: "btn btn-outline", data: { disable_with: "送信中..." } %>
                </div>
            <% end %>
    </main>
    <%= render 'layouts/footer' %>
</body>
</html>

<script>
    document.addEventListener("turbo:load", function() {
        const imageInput = document.querySelector('#user_image');
        const imagePreview = document.getElementById('image-preview');

        imageInput.addEventListener('change', function(event) {
            const file = event.target.files[0];
            if (file) {
                const reader = new FileReader();

                reader.onload = function(e) {
                    imagePreview.innerHTML = ''; // Clear the existing preview
                    const img = document.createElement('img');
                    img.src = e.target.result;
                    img.classList.add('rounded-lg', 'max-w-full', 'h-auto');
                    imagePreview.appendChild(img); // Append the new image
                };

                reader.readAsDataURL(file);
            }
        });
    });
</script>
```

**Comment by monaka0309** [comment]
ありがとうございます。
emailを取得することで解決できました。
ありがとうございました。

### sorcery.rb
```
  config.line.user_info_mapping = {name: 'displayName', email: 'userId'}
```
